#!/usr/bin/env node
/**
 * Generate languages/poetheme-en_US.po from poetheme.pot.
 *
 * The theme's source strings are written in Italian. This produces an English
 * (en_US) catalogue: front-end strings and the main admin labels are translated
 * here; long-form admin descriptions are left empty and fall back to the source
 * string (standard gettext behaviour). Re-run after updating the .pot, then
 * `npm run build:mo` to compile the binary.
 */
const fs = require('fs');
const path = require('path');
const { po } = require('gettext-parser');

const langDir = path.join(__dirname, '..', 'languages');
const potPath = path.join(langDir, 'poetheme.pot');
const poPath = path.join(langDir, 'poetheme-en_US.po');

// Italian source string -> English translation.
const dict = {
  // --- Front-end: navigation & structure ---
  'Contenuto principale': 'Main content',
  'Menù principale': 'Main menu',
  'Navigazione principale': 'Primary navigation',
  'Navigazione rapida': 'Quick navigation',
  'Apri il menù principale': 'Open main menu',
  'Chiudi il menù principale': 'Close main menu',
  'Apri il menu principale': 'Open main menu',
  'Espandi menu laterale': 'Expand sidebar menu',
  'Comprimi menu laterale': 'Collapse sidebar menu',
  'Menu laterale del sito': 'Site sidebar menu',
  'Apri menu mobile': 'Open mobile menu',
  'Chiudi menu mobile': 'Close mobile menu',
  'Apri ricerca': 'Open search',
  'Cerca': 'Search',
  'Cerca prodotti': 'Search products',
  'Cerca prodotti...': 'Search products...',
  'Autore del sito': 'Site author',
  'Vai a %s': 'Go to %s',
  // --- Front-end: search & 404 ---
  'Pagina non trovata': 'Page not found',
  'Risultati della ricerca per "%s"': 'Search results for "%s"',
  // --- Front-end: contact actions ---
  'Apri chat WhatsApp': 'Open WhatsApp chat',
  'Apri la posizione su Google Maps': 'Open location on Google Maps',
  'Chiama il numero': 'Call the number',
  'Invia una email': 'Send an email',
  'Informazioni rapide': 'Quick info',
  'Informazioni': 'Information',
  // --- Menu locations & widget areas ---
  'Menu informazioni': 'Info menu',
  'Menu fascia App Sidebar': 'App Sidebar strip menu',
  'Area widget': 'Widget area',
  'Aree servite': 'Areas served',
  'Widget pagina': 'Page widgets',
  'Widget Footer': 'Footer widgets',
  // --- Style Studio ---
  'Style Studio': 'Style Studio',
  'Complementare': 'Complementary',
  'Analoga': 'Analogous',
  'Triade': 'Triadic',
  'Complementare divisa': 'Split complementary',
  'Monocromatica': 'Monochromatic',
  'Nome template': 'Template name',
  'Colore brand': 'Brand color',
  'Armonia': 'Harmony',
  'Modalità': 'Mode',
  'Chiara': 'Light',
  'Scura': 'Dark',
  'Usa il colore accento per i pulsanti': 'Use the accent color for buttons',
  'Salva come template': 'Save as template',
  'Salva e applica': 'Save and apply',
  'La mia palette': 'My palette',
  'Palette generata': 'Generated palette',
  'Titolo di esempio': 'Sample heading',
  'Pulsante': 'Button',
  'Insufficiente': 'Low',
  'Tipografia': 'Typography',
  'Font titoli': 'Heading font',
  'Font testo': 'Body font',
  'Predefinito del tema': 'Theme default',
  'Dimensione base testo (rem)': 'Base text size (rem)',
  'Scala tipografica': 'Type scale',
  'Compatta (1.125)': 'Compact (1.125)',
  'Terza minore (1.2)': 'Minor third (1.2)',
  'Terza maggiore (1.25)': 'Major third (1.25)',
  'Quarta giusta (1.333)': 'Perfect fourth (1.333)',
  'Ampia (1.414)': 'Wide (1.414)',
  'Densità e forme': 'Density and shapes',
  'Densità': 'Density',
  'Compatta': 'Compact',
  'Comoda': 'Comfortable',
  'Ariosa': 'Spacious',
  'Arrotondamento pulsanti': 'Button rounding',
  'Squadrato': 'Squared',
  'Morbido': 'Soft',
  'Pillola': 'Pill',
  'Iscriviti': 'Subscribe',
  'collegamento': 'link',
  'Titolo della pagina di esempio': 'Sample page title',
  'Di Redazione · 12 giugno 2026 · 5 min di lettura': 'By Editorial · June 12, 2026 · 5 min read',
  'Un paragrafo introduttivo con un ': 'An introductory paragraph with a ',
  ' e del testo in ': ' and some text in ',
  'grassetto': 'bold',
  'Una sezione importante': 'An important section',
  'Testo di esempio con del codice ': 'Sample text with some code ',
  'Primo punto elenco': 'First list item',
  'Secondo punto elenco': 'Second list item',
  'Terzo punto elenco': 'Third list item',
  '“Una citazione che mette in risalto un concetto chiave del contenuto.”': '“A quote highlighting a key concept of the content.”',
  'Immagine in evidenza': 'Featured image',
  'Didascalia dell’immagine di esempio.': 'Sample image caption.',
  'Dettagli e dati': 'Details and data',
  'Primo passaggio': 'First step',
  'Secondo passaggio': 'Second step',
  'Terzo passaggio': 'Third step',
  'Piano': 'Plan',
  'Prezzo': 'Price',
  'Azione principale': 'Primary action',
  'Secondaria': 'Secondary',
  'Preset pronti': 'Ready-made presets',
  'Parti da uno stile predefinito con un clic, poi personalizzalo a piacere.': 'Start from a predefined style with one click, then customize it as you like.',
  'Aziendale': 'Corporate',
  'Editoriale': 'Editorial',
  'Notturno': 'Nocturne',
  'Natura': 'Nature',
  'Ispirami': 'Inspire me',
  'Stai modificando: %s': 'You are editing: %s',
  'Salva come palette': 'Save as palette',
  'Aggiorna palette': 'Update palette',
  'Aggiorna e applica': 'Update and apply',
  'Palette creata.': 'Palette created.',
  'Palette aggiornata.': 'Palette updated.',
  'Crea nuova palette': 'Create new palette',
  'Preset': 'Preset',
  'Modifica': 'Edit',
  'Personalizzazione avanzata': 'Advanced customization',
  'Rifinisci i singoli colori e le dimensioni partendo dai valori generati.': 'Refine individual colors and sizes starting from the generated values.',
  'Reimposta tutte le personalizzazioni': 'Reset all customizations',
  'Reimposta al valore generato': 'Reset to the generated value',
  'Dimensioni testo': 'Text sizes',
  'Voci di menu': 'Menu items',
  'Sfondo pulsante CTA': 'CTA button background',
  'Testo pulsante CTA': 'CTA button text',
  'Sfondo top bar': 'Top bar background',
  'Sfondo footer': 'Footer background',
  'Testo footer': 'Footer text',
  'Dimensione testo': 'Text size',
  'Dimensione H1': 'H1 size',
  'Dimensione H2': 'H2 size',
  'Dimensione H3': 'H3 size',
  'Dimensione H4': 'H4 size',
  'Dimensione H5': 'H5 size',
  'Dimensione H6': 'H6 size',
  'Titoli': 'Headings',
  'Testo top bar': 'Top bar text',
  'Titoli footer': 'Footer headings',
  'Layout e dettagli': 'Layout and details',
  'Larghezza sito': 'Site width',
  'Raggio pulsanti': 'Button radius',
  'Sottolinea i link': 'Underline links',
  'Largo': 'Wide',
  'Riquadro': 'Boxed',
  'Interlinea testo': 'Text line height',
  'Interlinea titoli': 'Heading line height',
  'Spaziatura titoli': 'Heading spacing',
  'Gestito da Style Studio': 'Managed by Style Studio',
  'Colori, font e dimensioni si configurano ora da Style Studio, in modo coordinato e con anteprima dal vivo. Questa pagina resta disponibile per le impostazioni avanzate non ancora migrate.': 'Colors, fonts and sizes are now configured from Style Studio, in a coordinated way with a live preview. This page remains available for advanced settings not yet migrated.',
  'Apri Style Studio': 'Open Style Studio',
  'Sfondo voci di menu': 'Menu items background',
  'Sfondo voce attiva': 'Active item background',
  'Sfondo titoli': 'Headings background',
  'Sfondo titoli footer': 'Footer headings background',
  'Dimensione testo CTA': 'CTA text size',
  'Dimensione testo top bar': 'Top bar text size',
  'Dimensione testo footer': 'Footer text size',
  'Dimensione titoli footer': 'Footer headings size',
  'Testata trasparente': 'Transparent header',
  'Nascondi ombra testata': 'Hide header shadow',
  'Footer trasparente': 'Transparent footer',
  'Trasparente': 'Transparent',
  'Reset': 'Reset',
  'Riporta il template allo stato iniziale': 'Reset the template to its initial state',
  // --- Fonts ---
  'Altri font': 'Other fonts',
  'Regolare': 'Regular',
  // --- Style palettes ---
  'Palette cromatica e stile': 'Color & style palette',
  'Palette e stile': 'Palettes & style',
  'Scarica JSON di esempio': 'Download example JSON',
  'Importa palette': 'Import palette',
  'Palette disponibili': 'Available palettes',
  'Applica': 'Apply',
  'Esporta': 'Export',
  'Elimina': 'Delete',
  'Attiva': 'Active',
  'Disattiva palette': 'Deactivate palette',
  'Palette importata con successo.': 'Palette imported successfully.',
  'Palette applicata.': 'Palette applied.',
  'Palette eliminata.': 'Palette deleted.',
  'Il file JSON non è valido.': 'The JSON file is not valid.',
  // --- Admin: page & section titles ---
  'Impostazioni generali': 'General settings',
  'Impostazioni pagina': 'Page settings',
  'Impostazioni sottointestazione': 'Subheader settings',
  'Impostazioni testata': 'Header settings',
  'Gestione Colori': 'Color management',
  'Gestione Font': 'Font management',
  'Tipografia': 'Typography',
  'Tipi di carattere': 'Fonts',
  'Globale': 'Global',
  'Layout': 'Layout',
  'Testata': 'Header',
  'Sottointestazione': 'Subheader',
  'Piè di pagina': 'Footer',
  'Intestazione': 'Header',
  'Barra superiore': 'Top bar',
  'Logo': 'Logo',
  'Call to Action': 'Call to action',
  'Icone social': 'Social icons',
  'CSS personalizzato': 'Custom CSS',
  'Breadcrumb': 'Breadcrumb',
  'Interfaccia': 'Interface',
  'Posizione': 'Position',
  'Dimensione': 'Size',
  'Contenuti': 'Content',
  'Contenuti e sfondi': 'Content and backgrounds',
  'Trasparenza': 'Transparency',
  'Margine': 'Margin',
  'Padding': 'Padding',
  'Varie': 'Miscellaneous',
  'Comunicazione': 'Communication',
  // --- Admin: common controls & labels ---
  'Sì': 'Yes',
  'No': 'No',
  'Predefinito': 'Default',
  'Automatico': 'Automatic',
  'Alto': 'High',
  'Basso': 'Low',
  'Destra': 'Right',
  'Sinistra': 'Left',
  'Anteprima': 'Preview',
  'Seleziona layout': 'Select layout',
  'Scegli icona': 'Choose icon',
  "Scegli un'immagine di sfondo": 'Choose a background image',
  'Scegli immagine': 'Choose image',
  'Scegli un logo': 'Choose a logo',
  'Carica logo': 'Upload logo',
  'Rimuovi logo': 'Remove logo',
  'Rimuovi immagine': 'Remove image',
  'Rimuovi icona': 'Remove icon',
  'Rimuovi': 'Remove',
  'Rimuovi fascia': 'Remove time slot',
  'Usa immagine': 'Use image',
  'Usa questa immagine': 'Use this image',
  'Usa questo logo': 'Use this logo',
  'Usa logo': 'Use logo',
  'Seleziona immagine': 'Select image',
  'Seleziona dal Media': 'Select from Media Library',
  'Scegli immagine': 'Choose image',
  'Carica un logo': 'Upload a logo',
  'Aggiungi contatto': 'Add contact',
  'Aggiungi fascia oraria': 'Add time slot',
  'Scegli icona': 'Choose icon',
  "Seleziona un'icona": 'Select an icon',
  'Nessuna icona selezionata': 'No icon selected',
  'Cerca tra le icone...': 'Search icons...',
  'Nessuna icona corrisponde ai criteri di ricerca.': 'No icon matches your search.',
  'Nessun logo selezionato.': 'No logo selected.',
  'Nessuna immagine selezionata.': 'No image selected.',
  'Nessun contatto ancora configurato.': 'No contact configured yet.',
  'Nessuna fascia oraria aggiunta.': 'No time slot added.',
  'Nessuna fascia oraria configurata.': 'No time slot configured.',
  'Icona Lucide': 'Lucide icon',
  // --- Admin: layout / width ---
  'Larghezza box': 'Boxed width',
  'Larghezza piena (100% della pagina)': 'Full width (100% of the page)',
  'Larghezza sito (px)': 'Site width (px)',
  'Numero di righe': 'Number of rows',
  'Numero di righe': 'Number of rows',
  'Layout riga %d': 'Row %d layout',
  'Layout con sidebar verticale collassabile, logo in alto, menu laterale, titolo pagina e breadcrumb nell’area contenuto.':
    'Layout with a collapsible vertical sidebar, logo on top, side menu, page title and breadcrumb in the content area.',
  // --- Admin: header layout choices ---
  'Layout 1 – Classico': 'Layout 1 – Classic',
  'Layout 2 – Centrato': 'Layout 2 – Centered',
  'Layout 3 – Minimal': 'Layout 3 – Minimal',
  'Layout 4 – Vetrina': 'Layout 4 – Showcase',
  'Layout 5 – Overlay': 'Layout 5 – Overlay',
  'Layout 6 – Sticky': 'Layout 6 – Sticky',
  'Layout 7 – Promo': 'Layout 7 – Promo',
  'Layout 8 – E-commerce': 'Layout 8 – E-commerce',
  // --- Admin: toggles (show/hide) ---
  'Mostra il titolo della pagina': 'Show the page title',
  'Mostra i breadcrumbs': 'Show breadcrumbs',
  'Mostra sottointestazione': 'Show subheader',
  'Mostra il piè di pagina': 'Show the footer',
  'Mostra il pulsante Call to Action.': 'Show the Call to Action button.',
  'Mostra il testo in grassetto': 'Show text in bold',
  'Mostra il titolo del sito al posto del logo': 'Show the site title instead of the logo',
  'Nascondi titolo pagina': 'Hide page title',
  'Nascondi breadcrumbs': 'Hide breadcrumbs',
  'Rimuovi il padding superiore del contenuto': 'Remove the top padding of the content',
  'Rimuovi ombra della testata': 'Remove header shadow',
  'Rendi la testata trasparente': 'Make the header transparent',
  // --- Admin: schema / publisher ---
  'SEO Schema': 'SEO Schema',
  'Attiva output JSON-LD': 'Enable JSON-LD output',
  'Tipologia di publisher': 'Publisher type',
  'Tipologia di contatto': 'Contact type',
  'Contatti del publisher': 'Publisher contacts',
  'Orari di apertura': 'Opening hours',
  'Fasce orarie di disponibilità': 'Availability time slots',
  'Fascia oraria': 'Time slot',
  'Aggiungi fascia oraria': 'Add time slot',
  'Apre alle': 'Opens at',
  'Chiude alle': 'Closes at',
  'Valido dal': 'Valid from',
  'Valido fino al': 'Valid until',
  'Lingue supportate': 'Supported languages',
  'Email': 'Email',
  'Telefono': 'Phone',
  'Contatto': 'Contact',
  'URL di riferimento': 'Reference URL',
  'Immagini della sede': 'Venue images',
  // --- Days of week ---
  'Lunedì': 'Monday',
  'Martedì': 'Tuesday',
  'Mercoledì': 'Wednesday',
  'Giovedì': 'Thursday',
  'Venerdì': 'Friday',
  'Sabato': 'Saturday',
  'Domenica': 'Sunday',
  'Tutte': 'All',
  // --- Admin: footer / credits ---
  'Testo credits': 'Credits text',
  'Visualizza i credits.': 'Display the credits.',
  'Mostra la barra superiore con informazioni e social.': 'Show the top bar with info and social links.',
  // --- Listings ---
  'Leggi tutto': 'Read more',
  'Potrebbe esserti utile anche': 'You might also find useful',
  // --- Floating scroll actions ---
  'Torna su': 'Back to top',
  'Vai ai commenti': 'Go to comments',
  'Condividi': 'Share',
  'Azioni rapide': 'Quick actions',
  'Copia il link:': 'Copy the link:',
  'Link copiato negli appunti.': 'Link copied to the clipboard.',
  // --- Sample / demo content ---
  'Titolo di esempio H1': 'Sample heading H1',
  'Titolo di esempio H2': 'Sample heading H2',
  'Titolo di esempio H3': 'Sample heading H3',
  'Titolo di esempio H4': 'Sample heading H4',
  'Titolo di esempio H5': 'Sample heading H5',
  'Titolo di esempio H6': 'Sample heading H6',
  'Titolo di pagina di esempio': 'Sample page title',
  'Titolo di articolo di esempio': 'Sample post title',
  'Titolo di categoria di esempio': 'Sample category title',
  'Titolo widget di esempio': 'Sample widget title',
  'Questo è un esempio di paragrafo con il font selezionato.':
    'This is a sample paragraph using the selected font.',
  'Call to action di esempio': 'Sample call to action',
  'Testo della barra superiore di esempio.': 'Sample top bar text.',
  'Testo del widget footer di esempio.': 'Sample footer widget text.',
};

const parsed = po.parse(fs.readFileSync(potPath));

// Header for en_US.
const h = parsed.headers;
h.Language = 'en_US';
h['Plural-Forms'] = 'nplurals=2; plural=(n != 1);';
h['PO-Revision-Date'] = new Date().toISOString().replace('T', ' ').slice(0, 16) + '+0000';
h['Last-Translator'] = 'PoeTheme';
h['Language-Team'] = 'English';

let translated = 0;
Object.values(parsed.translations).forEach((ctx) => {
  Object.values(ctx).forEach((entry) => {
    if (!entry.msgid) return; // skip header
    if (Object.prototype.hasOwnProperty.call(dict, entry.msgid)) {
      const en = dict[entry.msgid];
      if (entry.msgid_plural) {
        entry.msgstr = [en, en];
      } else {
        entry.msgstr = [en];
      }
      translated += 1;
    }
  });
});

// gettext-parser keeps the `fuzzy` flag from the .pot header comment; drop it.
if (parsed.translations[''] && parsed.translations[''][''] && parsed.translations[''][''].comments) {
  delete parsed.translations[''][''].comments.flag;
}

fs.writeFileSync(poPath, po.compile(parsed));
console.log(`Wrote ${path.basename(poPath)} (${translated} strings translated, rest fall back to source).`);
